### ISSUE TITLE
The 'Pods' target has transitive dependencies that include static binaries

### ISSUE THREAD

**Issue by CocoaBob** [393385724/DDSocial#1]
`pod install` 出现以下错误
`The 'Pods' target has transitive dependencies that include static binaries: (/Documents/GIT-GitHub/Soyou/Pods/TwitterKit/TwitterKit.framework and /Documents/GIT-GitHub/Soyou/Pods/WeiboSDK/libWeiboSDK/libWeiboSDK.a)`
不知道这个问题该如何解决，上网找了一圈，貌似是 Cocoapods 不支持依赖库包含静态库？
看到微信的静态库已经拷过来了，我想 Twitter、微博 的静态库也应该直接拷过来吧？
另外，请问有计划支持 Instagram 吗？毕竟现在 Instagram 的用户数量比 Twitter 还多~
最近一直在找一个比较好的第三方登录库，之前我 fork 了这个，请参考：`https://github.com/CocoaBob/LXMThirdLoginManager`

**Comment by CocoaBob** [comment]
`Podfile` 里不用 `use_frameworks!` 即可，但随之而来的问题是很多 Swift 类库必须用它……改了一天，终于改完了，能安装 DDSocial 了……

**Comment by 393385724** [comment]
Instagram 还没有研究可以加入进来 ，很高兴你能关注这个作品，我们一起来完善他吧。

**Comment by CocoaBob** [comment]
目前在我的 fork 中已经实现了 Tencent 和 Weibo 的登录（获得 openID 和 acessToken），但在我的 fork 中，我删掉了小米相关的内容，所以不能轻易提交 Pull Request。
所以还是麻烦您从我的 fork 里把最后两次 commit 的内容复制过来吧~
