### ISSUE TITLE
MiLiaoAppSDK 有很多问题啊

### ISSUE THREAD

**Issue by CocoaBob** [393385724/DDSocial#2]
不支持 bitcode，而且模拟器编译时出现了 62 个路径错误
`warning: (x86_64) /Users/wangyihe/ZWL/MiLiao2014/XiaomiShared/build/MiLiaoAppSDK.build/Debug-iphonesimulator/MiLiaoAppSDK.build/Objects-normal/x86_64/MLUrlCoder.o unable to open object file: No such file or directory`
建议不要支持米聊了……

**Comment by CocoaBob** [comment]
在我的 fork 里彻底删掉米聊和小米之后，清爽多了…
可以在 `Podfile` 里配置成我的 fork 来测试，估计你不感兴趣啦：
`pod "DDSocial", :podspec => 'https://raw.githubusercontent.com/CocoaBob/DDSocial/master/DDSocial.podspec', :commit => :head'`

不过还有两个关于微博的警告，先去睡了，有空再看看~

```
while processing /Documents/Git/Soyou/Pods/WeiboSDK/libWeiboSDK/libWeiboSDK.a(WBSDKNormalWebViewController.o):
warning: /var/folders/1n/49myhky1215gnqd43rvhl7cw0000gn/C/com.apple.DeveloperTools/7.1-7B91b/Xcode/SharedPrecompiledHeaders/WeiboSDK-Prefix-gqhtrdqotppcdeawptffppdogrrt/WeiboSDK-Prefix.pch.pch: No such file or directory
while processing /Documents/Git/Soyou/Pods/WeiboSDK/libWeiboSDK/libWeiboSDK.a(WBSDKFMDatabasePool.o):
warning: /var/folders/1n/49myhky1215gnqd43rvhl7cw0000gn/C/com.apple.DeveloperTools/7.1-7B91b/Xcode/SharedPrecompiledHeaders/WeiboSDK-Prefix-fogwkpxcnbmurgcxscaighjsslvf/WeiboSDK-Prefix.pch.pch: No such file or directory
```

**Comment by CocoaBob** [comment]
> 不是米聊不支持 是DDMISDK不支持bitcode 还正在优化中
> 
> `pod 'DDSocial/Share', :git => 'https://github.com/393385724/DDSocial.git'`

DDMISDK 的官方有没有近期支持 bitcode 的说法？不能因为它而让整个项目都不支持 bitcode 吧…

**Comment by 393385724** [comment]
小米的授权 维护更新很慢，你也可以使用 pod ‘DDSocial/Tencent’ 和 pod ‘DDSocial/WeChat’ 自己实现分享 授权，并不一定基于DDSocialShareHandler

**Comment by 393385724** [comment]
每一个三方都可以是一个独立的模块被引用 单独使用的，设计有不合理的地方还往多指正

**Comment by CocoaBob** [comment]
我看 DDSocialShareHandler 里面关于 Tencent 和 WeChat 的部分是空的，我以为是没实现，就顺手实现了一下。包括 Twitter 也是，正在实现中……
可以在 Cocoapods 里配置使用指定的第三方独立模块吗？

**Comment by 393385724** [comment]
可以的 ，DDSocialShareHandler我在本地实现了，所以不必自己再去实现，近期我会在持续维护，    share.dependency 'DDSocial/Tencent'
    pod 'DDSocial/Wechat'
    pod 'DDSocial/Sina'
    pod 'DDSocial/Facebook'
    pod 'DDSocial/Twitter'
    pod 'DDSocial/MiLiao'
以这种方式引入 相对而言更灵活，你可以针对每个子模块做提交

**Comment by CocoaBob** [comment]
多谢指点！试了一下，果然可以按模块安装，学习了~
但如果我想使用 'Share' 模块（用来注册 key/secret）和 'Auth' 模块的话（用来登录），就会把它俩依赖的小米相关模块全都安装上去了…
『本地实现 DDSocialShareHandler』，是在我的项目里复制一遍 DDSocialShareHandler 的意思吗？

**Comment by CocoaBob** [comment]
DDSocialShareHandler、DDSocialAuthHandler 里的各子模块 handler，可以用 protocol 来统一调用接口，这样就不需要 #import 了，也就不需要让 'Share' 和 'Auth' 去依赖所有子模块了。我去实现一下看看。

**Comment by CocoaBob** [comment]
重构完毕，现在可以真正独立安装每一个模块了！
（但我把 DDSocialAuthHandler 里的 DDMISDK 相关的代码删掉了，这部分代码引用了你的另一个类库，改不了…而且它的 register 代码应该放在 DDSocialShareHandler 里吧？）
目前可以通过以下配置来独立获得模块（我把 MILiao 和 MI 注释掉了，以前是不可以的）：

```
pod "DDSocial/Auth",    :git => 'git://github.com/CocoaBob/DDSocial', :commit => 'c96140ba9bf3aba7102c32a18ea37de5d810b258'
pod "DDSocial/Share",   :git => 'git://github.com/CocoaBob/DDSocial', :commit => 'c96140ba9bf3aba7102c32a18ea37de5d810b258'
pod "DDSocial/Tencent", :git => 'git://github.com/CocoaBob/DDSocial', :commit => 'c96140ba9bf3aba7102c32a18ea37de5d810b258'
pod "DDSocial/Wechat",  :git => 'git://github.com/CocoaBob/DDSocial', :commit => 'c96140ba9bf3aba7102c32a18ea37de5d810b258'
pod "DDSocial/Sina",    :git => 'git://github.com/CocoaBob/DDSocial', :commit => 'c96140ba9bf3aba7102c32a18ea37de5d810b258'
#pod "DDSocial/MiLiao",  :git => 'git://github.com/CocoaBob/DDSocial', :commit => 'c96140ba9bf3aba7102c32a18ea37de5d810b258'
#pod "DDSocial/MI",      :git => 'git://github.com/CocoaBob/DDSocial', :commit => 'c96140ba9bf3aba7102c32a18ea37de5d810b258'
pod "DDSocial/Facebook",:git => 'git://github.com/CocoaBob/DDSocial', :commit => 'c96140ba9bf3aba7102c32a18ea37de5d810b258'
pod "DDSocial/Twitter", :git => 'git://github.com/CocoaBob/DDSocial', :commit => 'c96140ba9bf3aba7102c32a18ea37de5d810b258'
pod "DDSocial/Google",  :git => 'git://github.com/CocoaBob/DDSocial', :commit => 'c96140ba9bf3aba7102c32a18ea37de5d810b258'
```

如果没有问题的话，我提交 PullRequest 吧？但是需要麻烦你想办法解决 DDMISDK 的整合问题。

**Comment by 393385724** [comment]
好的，你先提交，这两天手头上有其他的事，稍后我会看一下
