### ISSUE TITLE
libWeChatSDK 版本太旧不支持 bitcode

### ISSUE THREAD

**Issue by CocoaBob** [393385724/DDSocial#3]
在我的 fork 里修改了一下 podspec，将 libWeChatSDK 改成了 dependency

```
s.subspec 'Wechat' do |wechat|
  wechat.source_files = 'DDSocial/Wechat/*.{h,m}'
  wechat.dependency 'libWeChatSDK'
  wechat.dependency 'DDSocial/Core'
end
```

可以拿我的 fork 做测试
`pod "DDSocial", :podspec => 'https://raw.githubusercontent.com/CocoaBob/DDSocial/master/DDSocial.podspec', :commit => 'c96140ba9bf3aba7102c32a18ea37de5d810b258'`

唯一的问题是，libWeChatSDK 这个 pod 并没有更新到最新版，所以需要在上面这行配置的前面再添加一个配置以获得最新版（暂时在我的 fork 内，我已尝试各种办法去通知libWeChatSDK的维护者，无果……）
`pod "libWeChatSDK", :git => 'git://github.com/CocoaBob/libWeChatSDK', :commit => 'bb4387498ef2974189e8270928f62a1cd3a8ef62'`

**Comment by 393385724** [comment]
不是米聊不支持  是DDMISDK不支持bitcode,pod 'DDSocial/Share', :git => 'https://github.com/393385724/DDSocial.git',还正在优化中

**Comment by CocoaBob** [comment]
DDMISDK 的官方有没有近期支持 bitcode 的说法？不能因为它而让整个项目都不支持 bitcode 吧…
目前在我的 fork 中已经实现了 Tencent 和 Weibo 的登录（获得 openID 和 acessToken）。
我现在卡在 Google 登录会崩溃的问题上。不知你试过 Google 登录没？具体应该怎么用？
